### ISSUE TITLE
Import non-dialect-specific parts from Virtual Schemas

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schema-common-jdbc#1]
## Situation

We have common parts of Virtual Schemas based on JDBC-access in the [Virtual Schemas](https://github.com/exasol/virtual-schemas) repository. This part is useful for other projects besides the existing dialects.

## Acceptance Criteria

1. Common part extracted
2. Maven module built

**Comment by AnastasiiaSergienko** [comment]
Closed with #2
