### ISSUE TITLE
Add Registration for ExaLoader to documentation

### ISSUE THREAD

**Issue by ckunki** [exasol/virtual-schema-common-jdbc#118]
Currently Registering a JDBC driver for ExaLoader is described in https://github.com/exasol/docker-db/#installing-custom-jdbc-drivers. However I do not see a specific relationship to docker db.

See also [postgresql user guide](https://github.com/exasol/postgresql-virtual-schema/blob/main/doc/user_guide/postgresql_user_guide.md).

In my opinion this piece of documentation 
* should be contained in the official default documentation, e.g. here 
https://docs.exasol.com/db/latest/database_concepts/virtual_schema/user_guide.htm?Highlight=exaloader#Deploy
* or could alternatively go to [virtual-schema-common-jdbc](https://github.com/exasol/virtual-schema-common-jdbc).

**Comment by redcatbear** [comment]
Moved to DOC-2511.
