### ISSUE TITLE
Locale specific formatting of decimal point

### ISSUE THREAD

**Issue by kaklakariada** [exasol/virtual-schema-common-jdbc#119]
Method `SqlGenerationVisitor.visit(SqlLiteralDouble)` returns values with decimal point `,` when the locale is set to e.g. `en_DE`.

This is unexpected, the visit method should always return decimal point `.` independent of the locale.

Other methods may also be affected.

**Comment by ckunki** [comment]
see https://github.com/exasol/hive-virtual-schema/issues/28
