### ISSUE TITLE
Remove dialect-level plug-in mechanism

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schema-common-jdbc#86]
## Situation

We extracted each dialect into its own repository. There is now a 1 : 1 relationship between adapter and dialect. This makes the current dialect loading superfluous.

Fixes #63.

## Acceptance criteria

* Dialect Registry is removed
* Single dialect is injected

**Comment by chiaradiamarcelo** [comment]
It also fixes #62.
